import type { Operation } from "@hermes-office/protocol";
import type { RuntimeMessage } from "./i18n";

export type ProfileStatus = "working" | "waiting" | "idle" | "blocked";

export type Profile = {
  id: string;
  name: string;
  role: string;
  status: ProfileStatus;
  color: string;
  sessions: number;
  taskCount: number;
  memoryBytes: number;
  memoryNote: string;
  skills: string[];
  inheritedSkills: string[];
};

export type ChatMessage = {
  id: string;
  from: "user" | "agent" | "tool";
  kind?: "steer" | undefined;
  body: string;
  /** Locale-neutral copy generated by Office itself. Hermes-provided text stays in body. */
  presentation?: { kind: "tool-fallback"; name?: string | undefined; phase: "running" | "complete" } | undefined;
  at: string;
  status?: "streaming" | "complete" | "failed" | "cancelled";
};

export type ChatConnectionState = "disconnected" | "connecting" | "ready" | "error";
export type ChatHistoryState = "unloaded" | "loading" | "loaded" | "error";

export type ApprovalChoice = "once" | "session" | "always" | "deny";

export type ChatPendingInteraction =
  | {
      id: string;
      kind: "clarify";
      requestId: string;
      question: string;
      choices: string[];
      submitting: boolean;
      error?: RuntimeMessage | undefined;
    }
  | {
      id: string;
      kind: "approval";
      approvalId: string;
      command?: string | undefined;
      description?: string | undefined;
      choices: ApprovalChoice[];
      allowPermanent: boolean;
      submitting: boolean;
      error?: RuntimeMessage | undefined;
    };

export type ChatSession = {
  /** Stable UI identity. It can exist before Hermes persists a session. */
  id: string;
  /** Durable Hermes state.db identity used by REST history and resume. */
  storedSessionId?: string | undefined;
  /** Process-local gateway identity, valid only for the current WebSocket. */
  liveSessionId?: string | undefined;
  profileId: string;
  title: string;
  /** Only local draft titles are translated at render time. Hermes titles remain verbatim. */
  titlePresentation?: "new-chat" | undefined;
  status: "streaming" | "ready" | "waiting";
  messages: ChatMessage[];
  connectionState?: ChatConnectionState;
  historyState?: ChatHistoryState;
  historyPartial?: boolean;
  historyNotice?: RuntimeMessage | undefined;
  errorMessage?: RuntimeMessage | undefined;
  remoteKind?: "demo" | "stored" | "draft" | undefined;
  streamingMessageId?: string | undefined;
  pendingInteraction?: ChatPendingInteraction | undefined;
  steerPending?: boolean | undefined;
  steerOperationId?: string | undefined;
  readOnly?: boolean;
};

export type TaskStatus = "triage" | "todo" | "scheduled" | "ready" | "running" | "blocked" | "review" | "done" | "archived";
export type TaskWritableStatus = "triage" | "todo" | "scheduled" | "ready" | "blocked" | "done" | "archived";

export type WorkTask = {
  id: string;
  title: string;
  body?: string | undefined;
  status: TaskStatus;
  assigneeId?: string | undefined;
  priority: "normal" | "high";
  priorityValue?: number;
  comments: number;
  latestSummary?: string | undefined;
  pending?: boolean;
};

export type TaskComment = {
  id: number;
  cardId: string;
  author: string;
  body: string;
  createdAt: number;
};

export type KanbanConnectionState = "idle" | "loading" | "ready" | "saving" | "error";

export type Surface = "office" | "kanban" | "library" | "settings";
export type InspectorTab = "chat" | "profile" | "skills" | "memory";
export type SettingsTab = "global" | "skills" | "soul" | "memory";

export type OfficeConnectionState = "demo" | "connecting" | "connected" | "degraded" | "error";
export type OfficeAccessState = "checking" | "login-required" | "submitting" | "authenticated" | "unavailable";

export type OfficeAccess = {
  state: OfficeAccessState;
  serverUrl: string;
  message: RuntimeMessage;
  failureCode?: "invalid" | "rate-limited" | "disabled" | "unavailable" | undefined;
  retryAfterSeconds?: number | undefined;
};

export type OfficeRuntimeState =
  | "unconfigured"
  | "starting"
  | "ready"
  | "stopping"
  | "stopped"
  | "unreachable"
  | "incompatible"
  | "error";

export type OfficeConnection = {
  state: OfficeConnectionState;
  source: "demo" | "server";
  serverUrl: string;
  runtime?: OfficeRuntimeState;
  protocolVersion?: number;
  generatedAt?: string;
  eventStream: "closed" | "connecting" | "open";
  message: RuntimeMessage;
};

export type OfficeSnapshotProfile = {
  id: string;
  name: string;
  activity: string;
  activeSessionCount: number;
};

export type OfficeInventoryPagination = {
  returned: number;
  available: number;
  total?: number;
  hasMore: boolean;
  truncated: boolean;
  partialFailures: number;
  nextCursor?: string;
};

export type OfficeSnapshot = {
  generatedAt: string;
  sequence: number;
  capabilities: {
    protocolVersion: number;
    serverVersion: string;
    runtime: { state: OfficeRuntimeState; hermesVersion?: string; adapterVersion?: string };
    access: {
      deviceId: string;
      tier: "viewer" | "operator" | "manager" | "owner";
      exposure: "loopback" | "tailnet" | "public";
      authentication: "desktop-capability" | "local-cookie" | "device-cookie" | "tailscale-identity" | "oidc";
      allowedOperations: Operation[];
    };
    features: Array<"chat" | "profiles" | "skills" | "memory" | "kanban" | "global-inheritance" | "demo">;
  };
  profiles: OfficeSnapshotProfile[];
  sessions: Array<{ id: string; profileId: string; title: string; activity: string }>;
  inventory: { profiles: OfficeInventoryPagination; sessions: OfficeInventoryPagination };
  boards: Array<{ id: string; name: string; cardCount: number }>;
};

export type OfficeSnapshotRequestIdentity = Readonly<{
  serverUrl: string;
  connectionGeneration: number;
  requestGeneration: number;
}>;
